{
 "title": "NGINX NAP - Attack Signatures",
 "description": "This Dashboard provides more visibility into the logs generated by NGINX App Protect. This is part of a series of NGINX App Protect Dashboards",
 "tags": [
  "nginx",
  "nap"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Accuracy",
    "query": "{\"find\": \"terms\", \"field\": \"signature-details.accuracy.keyword\", \"size\": 1000}"
   },
   {
    "name": "Context",
    "query": "{\"find\": \"terms\", \"field\": \"details.context.keyword\", \"size\": 1000}"
   },
   {
    "name": "Risk",
    "query": "{\"find\": \"terms\", \"field\": \"signature-details.risk.keyword\", \"size\": 1000}"
   },
   {
    "name": "Bots",
    "query": "{\"find\": \"terms\", \"field\": \"client_class.keyword\", \"size\": 1000}"
   },
   {
    "name": "CVEs",
    "query": "{\"find\": \"terms\", \"field\": \"sig_cves.keyword\", \"size\": 1000}"
   },
   {
    "name": "Policy",
    "query": "{\"find\": \"terms\", \"field\": \"policy_name.keyword\", \"size\": 1000}"
   },
   {
    "name": "Device",
    "query": "{\"find\": \"terms\", \"field\": \"logsource.keyword\", \"size\": 1000}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocked",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "request_status.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Signature Risk",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "signature-details.risk.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Bots",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "client_class.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Bot Name",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "bot_signature_name.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Blocking Exception",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "blocking_exception_reason.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Methods",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "method.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "CVEs",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "sig_cves.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "NOT sig_cves.keyword:\"N/A\" && signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Signature Hits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unique Signatures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "details.sig_data.sig_id.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "details.sig_data.sig_id.keyword",
       "id": "1",
       "type": "cardinality"
      }
     ],
     "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Signature Context",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "details.context.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      {
       "field": "details.sig_data.sig_id.keyword",
       "id": "3",
       "type": "cardinality"
      }
     ],
     "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Signature Accuracy",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "signature-details.accuracy.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "policy_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "URL Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@version",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "support_id.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Attackers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@version",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "source_host", "id": "1", "type": "cardinality" }
     ],
     "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source_host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "uri.keyword", "id": "3", "type": "cardinality" },
      { "field": "sig_id.keyword", "id": "4", "type": "cardinality" },
      { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 20 Signature Hits over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "signature-details.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "20" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Signature Names",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "signature-details.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "signature-details.sig_id",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "field": "signature-details.accuracy.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "signature-details.risk.keyword",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "source_host", "id": "3", "type": "cardinality" },
      { "field": "uri.keyword", "id": "4", "type": "cardinality" },
      { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "URLs",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uri.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "source_host", "id": "3", "type": "cardinality" },
      { "field": "sig_id.keyword", "id": "4", "type": "cardinality" },
      { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Parameter Context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Parameter Names",
     "type": "table",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "details.parameter_data.name.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
         "type": "terms"
        },
        {
         "field": "details.parameter_data.value.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "source_host", "id": "3", "type": "cardinality" },
        { "field": "uri.keyword", "id": "4", "type": "cardinality" },
        { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
       ],
       "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Parameter Values",
     "type": "table",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "details.parameter_data.value.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "source_host", "id": "3", "type": "cardinality" },
        { "field": "uri.keyword", "id": "4", "type": "cardinality" },
        { "field": "policy_name.keyword", "id": "5", "type": "cardinality" },
        {
         "field": "details.parameter_data.name.keyword",
         "id": "7",
         "type": "cardinality"
        }
       ],
       "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Parameter Context Logs",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "_exists_:details.parameter_data.value && signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Header Context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Header Names",
     "type": "table",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "details.header.header_name.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
         "type": "terms"
        },
        {
         "field": "details.header.header_value.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "source_host", "id": "3", "type": "cardinality" },
        { "field": "uri.keyword", "id": "4", "type": "cardinality" },
        { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
       ],
       "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Header Values",
     "type": "table",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 4 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "details.header.header_value.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "source_host", "id": "3", "type": "cardinality" },
        { "field": "uri.keyword", "id": "4", "type": "cardinality" },
        { "field": "policy_name.keyword", "id": "5", "type": "cardinality" },
        {
         "field": "details.header.header_name.keyword",
         "id": "7",
         "type": "cardinality"
        }
       ],
       "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Header Context Logs",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "_exists_:details.header && signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Cookie",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cookie Names",
     "type": "table",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "details.cookie.cookie_name.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
         "type": "terms"
        },
        {
         "field": "details.cookie.cookie_value.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "source_host", "id": "3", "type": "cardinality" },
        { "field": "uri.keyword", "id": "4", "type": "cardinality" },
        { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
       ],
       "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "All Cookie Values",
     "type": "table",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 5 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "details.cookie.cookie_value.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "source_host", "id": "3", "type": "cardinality" },
        { "field": "uri.keyword", "id": "4", "type": "cardinality" },
        { "field": "policy_name.keyword", "id": "5", "type": "cardinality" },
        {
         "field": "details.parameter_data.name.keyword",
         "id": "7",
         "type": "cardinality"
        }
       ],
       "query": "signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Cookie Context Logs",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "_exists_:details.cookie && signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "URL Context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Keyword Detected",
     "type": "table",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "details.sig_data.kw_data.buffer.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "source_host", "id": "3", "type": "cardinality" },
        { "field": "uri.keyword", "id": "4", "type": "cardinality" },
        { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
       ],
       "query": "details.context:url && signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "URL Context Logs",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "details.context:url && signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Keyword Detected",
     "type": "table",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "details.sig_data.kw_data.buffer.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "source_host", "id": "3", "type": "cardinality" },
        { "field": "uri.keyword", "id": "4", "type": "cardinality" },
        { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
       ],
       "query": "details.context:request && signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Request Context Logs",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "details.context:request && signature-details.accuracy.keyword:$Accuracy && details.context.keyword:$Context && signature-details.risk.keyword:$Risk && client_class.keyword:$Bots && sig_cves.keyword:$CVEs && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}