{
 "title": "NGINX NAP BOT Dashboard",
 "description": "This Dashboard provides more visibility into the Bot logs generated by NGINX App Protect. This is part of a series of NGINX App Protect Dashboards",
 "tags": [
  "nginx",
  "nap"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Status",
    "query": "{\"find\": \"terms\", \"field\": \"request_status.keyword\", \"size\": 1000}"
   },
   {
    "name": "IP",
    "query": "{\"find\": \"terms\", \"field\": \"ip_client\", \"size\": 1000}"
   },
   {
    "name": "Outcome",
    "query": "{\"find\": \"terms\", \"field\": \"outcome.keyword\", \"size\": 1000}"
   },
   {
    "name": "Bots",
    "query": "{\"find\": \"terms\", \"field\": \"client_class.keyword\", \"size\": 100}"
   },
   {
    "name": "Severity",
    "query": "{\"find\": \"terms\", \"field\": \"severity_label.keyword\", \"size\": 1000}"
   },
   {
    "name": "Device",
    "query": "{\"find\": \"terms\", \"field\": \"logsource.keyword\", \"size\": 1000}"
   },
   {
    "name": "Policy",
    "query": "{\"find\": \"terms\", \"field\": \"policy_name.keyword\", \"size\": 100}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocked",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "request_status.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Methods",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "method.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Blocking Exception",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "blocking_exception_reason.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Bot Applications",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "client_application.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Bot Types",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "client_class.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "BOT Categories",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 2 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "client_class.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Requests over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 2 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "client_class.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Outcome",
   "type": "stat",
   "description": "This report doesn't include browsers",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "request_status.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT client_class.keyword:Browser && request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bot Class Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 4, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "client_class.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "client_application.keyword", "id": "3", "type": "cardinality" },
      { "field": "uri.keyword", "id": "4", "type": "cardinality" },
      { "field": "source_host", "id": "5", "type": "cardinality" },
      { "field": "geoip.country_code2.keyword", "id": "6", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bot Signatures",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 11, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "bot_signature_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "uri.keyword", "id": "4", "type": "cardinality" },
      { "field": "source_host", "id": "5", "type": "cardinality" },
      { "field": "geoip.country_code2.keyword", "id": "6", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bot Category Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "bot_category.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "uri.keyword", "id": "4", "type": "cardinality" },
      { "field": "source_host", "id": "5", "type": "cardinality" },
      { "field": "geoip.country_code2.keyword", "id": "6", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unique Bot IPs",
   "type": "stat",
   "description": "Doesn't include Browser category",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source_host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "source_host", "id": "1", "type": "cardinality" }
     ],
     "query": "NOT client_class.keyword:Browser && request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "URLs",
   "type": "table",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uri.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "client_class.keyword", "id": "3", "type": "cardinality" },
      { "field": "bot_category.keyword", "id": "4", "type": "cardinality" },
      { "field": "bot_signature_name.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IPs",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 11, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ip_client",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "client_class.keyword", "id": "3", "type": "cardinality" },
      { "field": "bot_category.keyword", "id": "4", "type": "cardinality" },
      { "field": "bot_signature_name.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "geoip.country_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "client_class.keyword", "id": "3", "type": "cardinality" },
      { "field": "bot_category.keyword", "id": "4", "type": "cardinality" },
      { "field": "bot_signature_name.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Additional", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Bot Anomalies",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "bot_anomalies.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "uri.keyword", "id": "4", "type": "cardinality" },
      { "field": "source_host", "id": "5", "type": "cardinality" },
      { "field": "geoip.country_code2.keyword", "id": "6", "type": "cardinality" }
     ],
     "query": "NOT bot_anomalies.keyword:\"N/A\" && request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bots per Policies",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "policy_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "uri.keyword", "id": "4", "type": "cardinality" },
      { "field": "source_host", "id": "5", "type": "cardinality" },
      { "field": "geoip.country_code2.keyword", "id": "6", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bots per Device",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "logsource.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "uri.keyword", "id": "4", "type": "cardinality" },
      { "field": "source_host", "id": "5", "type": "cardinality" },
      { "field": "geoip.country_code2.keyword", "id": "6", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}