{
 "title": "NGINX NAP SupportID",
 "description": "This Dashboard provides more visibility into a single incident logged by NGINX App Protect. This is part of a series of NGINX App Protect Dashboards",
 "tags": [
  "nginx",
  "nap"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SupportID",
    "query": "{\"find\": \"terms\", \"field\": \"support_id.keyword\", \"size\": 1000}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction Status",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "request_status.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "support_id.keyword:$SupportID",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Signature Risk",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "signature-details.risk.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "support_id.keyword:$SupportID",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Violations",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@version",
         "id": "2",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "violations.keyword", "id": "1", "type": "cardinality" }
       ],
       "query": "support_id.keyword:$SupportID",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Threat Campaign",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@version",
         "id": "2",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "threat_campaign_names.keyword", "id": "1", "type": "cardinality" }
       ],
       "query": "NOT threat_campaign_names:\"N/A\" && support_id.keyword:$SupportID",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Signatures",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@version",
         "id": "2",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "sig_ids.keyword", "id": "1", "type": "cardinality" }
       ],
       "query": "support_id.keyword:$SupportID",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Signature Accuracy",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "signature-details.accuracy.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "support_id.keyword:$SupportID",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Signature Context",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "details.context.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "support_id.keyword:$SupportID",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Overall Information",
   "type": "table",
   "gridPos": { "h": 15, "w": 7, "x": 0, "y": 2 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Other Details",
   "type": "table",
   "gridPos": { "h": 15, "w": 7, "x": 7, "y": 2 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Signature Sets",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sig_set_names.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Violation List",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violations.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Violation List",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sub_violations.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "URL & Request Details",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Signatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Signature Names",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "signature-details.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "signature-details.sig_id",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "field": "signature-details.accuracy.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "signature-details.risk.keyword",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Signature Context",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "details.context.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Parameter Names",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "details.parameter_data.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "details.parameter_data.value.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Header Names",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "details.header.header_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "details.header.header_value.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cookie Names",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "details.cookie.cookie_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "details.cookie.cookie_value.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "URL Context",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "details.sig_data.kw_data.buffer.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "details.context.keyword:url && support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Request Context",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "details.sig_data.kw_data.buffer.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "details.context.keyword:request && support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Log Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Original Index",
   "type": "logs",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Decoded Index",
   "type": "logs",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "support_id.keyword:$SupportID",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}