{
 "title": "NGINX NAP Main Dashboard",
 "description": "This Dashboard provides more visibility into the logs generated by NGINX App Protect. This is part of a series of NGINX App Protect Dashboards",
 "tags": [
  "nginx",
  "nap"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Status",
    "query": "{\"find\": \"terms\", \"field\": \"request_status.keyword\", \"size\": 1000}"
   },
   {
    "name": "IP",
    "query": "{\"find\": \"terms\", \"field\": \"ip_client\", \"size\": 1000}"
   },
   {
    "name": "Outcome",
    "query": "{\"find\": \"terms\", \"field\": \"outcome.keyword\", \"size\": 1000}"
   },
   {
    "name": "Bots",
    "query": "{\"find\": \"terms\", \"field\": \"client_class.keyword\", \"size\": 100}"
   },
   {
    "name": "Severity",
    "query": "{\"find\": \"terms\", \"field\": \"severity_label.keyword\", \"size\": 1000}"
   },
   {
    "name": "Device",
    "query": "{\"find\": \"terms\", \"field\": \"logsource.keyword\", \"size\": 1000}"
   },
   {
    "name": "Policy",
    "query": "{\"find\": \"terms\", \"field\": \"policy_name.keyword\", \"size\": 100}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Attacks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "request_status.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "World Map",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "geoip.location", "id": "2", "settings": { "precision": "4" }, "type": "geohash_grid" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Attackers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source_host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "source_host", "id": "1", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "outcome_reason.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "severity_label.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bot Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "client_class.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "method.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Violations",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violations.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "30" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "source_host", "id": "3", "type": "cardinality" },
      { "field": "uri.keyword", "id": "4", "type": "cardinality" },
      { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Requests over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "request_status.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IP Addresses",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source_host",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "violations.keyword", "id": "3", "type": "cardinality" },
      { "field": "uri.keyword", "id": "4", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "NAP Policies",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 7, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "policy_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "logsource.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "source_host", "id": "3", "type": "cardinality" },
      { "field": "uri.keyword", "id": "4", "type": "cardinality" },
      { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Threat Campaign",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "threat_campaign_names.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "ip_client", "id": "1", "type": "cardinality" },
      { "id": "3", "type": "count" },
      { "field": "policy_name.keyword", "id": "4", "type": "cardinality" }
     ],
     "query": "NOT threat_campaign_names.keyword:\"N/A\" && request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "URLs",
   "type": "table",
   "gridPos": { "h": 18, "w": 11, "x": 0, "y": 38 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uri.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "source_host", "id": "3", "type": "cardinality" },
      { "field": "violations.keyword", "id": "4", "type": "cardinality" },
      { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Signature Names",
   "type": "table",
   "gridPos": { "h": 18, "w": 8, "x": 11, "y": 38 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sig_names.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "source_host", "id": "3", "type": "cardinality" },
      { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "NOT sig_names.keyword:\"N/A\"&& request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CVEs",
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 19, "y": 38 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sig_cves.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT sig_cves.keyword:\"N/A\"&& request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Subviolations",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 56 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sub_violations.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "source_host", "id": "3", "type": "cardinality" },
      { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "NOT sub_violations.keyword:\"N/A\" && request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 56 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "response_code.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "source_host", "id": "3", "type": "cardinality" },
      { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 56 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "geoip.country_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "source_host", "id": "3", "type": "cardinality" },
      { "field": "policy_name.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "request_status.keyword:$Status && ip_client:$IP && outcome.keyword:$Outcome && client_class.keyword:$Bots && severity_label.keyword:$Severity && policy_name.keyword:$Policy && logsource.keyword:$Device",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}